<div class="col-xs-2 col-sm-10" id="centerdisplay" style="padding-left: 140px; padding-top: 30px;">

    <form action="#" method="post">
        <h4>Select Assignment .CPP file to upload</h4><br>
        <input type="file" id="myFile"><br><br>
        <input type="button" class="btn btn-primary" value="Submit">
    </form><br>

    <h4 style="padding-top: 40px">Output Results</h4>
    <p>SOME THING HERE IS THWEWRWERFWIEFR WNRGJN
        ERJGN WEJNG WJNF WEJN JWEGN SOME THING HERE IS
        THWEWRWERFWIEFR WNRGJN ERJGN WEJNG WJNF WEJN JWEGN
        SOME THING HERE IS THWEWRWERFWIEFR WNRGJN ERJGN WEJNG
        WJNF WEJN JWEGN SOME THING HERE IS THWEWRWERFWIEFR WNRGJN
        ERJGN WEJNG WJNF WEJN JWEGN SOME THING HERE IS
        THWEWRWERFWIEFR WNRGJN ERJGN WEJNG WJNF WEJN JWEGN
        SOME THING HERE IS THWEWRWERFWIEFR WNRGJN ERJGN
        WEJNG WJNF WEJN JWEGN SOME THING HERE IS THWEWRWERFWIEFR
        WNRGJN ERJGN WEJNG WJNF WEJN JWEGN SOME THING HERE IS
        THWEWRWERFWIEFR WNRGJN ERJGN WEJNG WJNF WEJN JWEGN SOME
        THING HERE IS THWEWRWERFWIEFR WNRGJN ERJGN WEJNG WJNF
        WEJN JWEGN SOME THING HERE IS THWEWRWERFWIEFR WNRGJN
        ERJGN WEJNG WJNF WEJN JWEGN SOME THING HERE IS
        THWEWRWERFWIEFR WNRGJN ERJGN WEJNG WJNF WEJN JWEGN
        SOME THING HERE IS THWEWRWERFWIEFR WNRGJN ERJGN WEJNG
        WJNF WEJN JWEGN SOME THING HERE IS THWEWRWERFWIEFR WNRGJN
        ERJGN WEJNG WJNF WEJN JWEGN
    </p>

</div>
